import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Container from "@/components/global/Container";
import Provider from "./provider";

const geistSans = Geist({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Store",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={` ${geistSans.className}  antialiased`}>
				<Provider>
					<Navbar />
					<Container className="py-20">{children}</Container>
				</Provider>
			</body>
		</html>
	);
}
